### ISSUE TITLE
Unable to find freetype-config after downloading and compiling freetype2

### ISSUE THREAD

**Issue by greenchile99** [aseprite/freetype2#6]
Hello I downloaded freetype-2.11.1.tar.gz from here [https://sourceforge.net/projects/freetype/](URL).  I compiled it using ./configure && make && make install.  I can't find freetype-config in my path.  I'm thinking it is in a different location.  Thanks.

**Comment by dacap** [comment]
Hi @greenchile99, you might want to download the [official freetype](https://freetype.org/) from its website, and ask in their mailing list in case that you have any issue: https://freetype.org/contact.html#mailing-lists
